repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest revision
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v1.2.5a9
    hooks:
      - id: cfn-lint
        files: 'template/cloudformation.yml'



