repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest revision
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v1.2.5a9
    hooks:
      - id: cfn-lint
        files: 'template/cloudformation.yml'


#  - repo: https://github.com/psf/black  ##todo  surpresed as this is not the piority
#    rev: 19.10b0  # Use the latest stable version
#    hooks:
#      - id: black
#        language_version: python3.8  # Ensure this matches your environment

#  - repo: https://github.com/pycqa/flake8 ##todo surpresed as this is not the piority
#    rev: '3.8.4'  # Use the latest stable version
#    hooks:
#      - id: flake8
