#------------ci-cd pipeline starts here----------#
name: python CI/CD Pipeline Checks & Apply

on:
  push:
    branches:
      - dev
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - dev
      - feature/*
      - bugfix/*

jobs:
  checks-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt

    - name: Run unit tests
      run: python -m unittest discover -s src -p "test_app.py"
      continue-on-error: false

    - name: Lint Python files
      run: |
        pip install flake8
        flake8 src/
      continue-on-error: false

    - name: Run Bandit security scan
      run: |
        pip install bandit
        bandit -r src/
      continue-on-error: true

    - name: Perform static analysis with pylint
      run: |
        pip install pylint
        pylint src/
      continue-on-error: true

    - name: Check for outdated dependencies
      run: |
        pip install pip-review
        pip-review --local --auto
      continue-on-error: true

    - name: Debug Information
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Is merged: ${{ github.event.pull_request.merged }}"
        echo "Base ref: ${{ github.event.pull_request.base.ref }}"
        echo "Head ref: ${{ github.event.pull_request.head.ref }}"
        echo "Ref: ${{ github.ref }}"

#------------ci-cd pipeline checks here---------------#
